### PR TITLE
Fixed naming issues

### LINKED ISSUE #2: Add A Landing Page for Project Karoobar
Add a landing page with project Description, Logo, and Link to Repo 

- [x] Code

- [x] CI/CD (Github Actions to GitHub Pages)

- [ ] Domain (optional)

### PR DESCRIPTION
**Pull request by sohamtamboli**
Fixed naming convention issue

closes #2

### CODE REVIEW

File: pages/index.vue [hunk 1]
```diff
@@ -5,7 +5,7 @@
 </template>
 
 <script>
-import LandingPage from '@/components/landing'
+import LandingPage from '@/components/Landing'
```
Comment (pruthvi2103) [inline pages/index.vue]: Please rename the component file to 2-word format like LandingPage.vue

**Review by pruthvi2103 — APPROVED** [review]
LGTM
